### ISSUE TITLE
Telepítsd a Github Destktop alkalmazást

### ISSUE THREAD

**Issue by mt-andrea** [mt-andrea/OctoCat#4]
Töltsétek le és telepítsétek az alkalmazást az alábbi likről:
https://desktop.github.com/
Ha készen vagy írd meg ide megjegyzésben.

**Comment by mt-andrea** [comment]
nekem megvan

**Comment by aoekatalin** [comment]
Készen van

**Comment by Sudi0005** [comment]
Kész van

**Comment by Marsal99** [comment]
kész

**Comment by Kjanos141** [comment]
Kész
