### ISSUE TITLE
Telepítsd a NetBeans IDE 8.2 alkalmazást

### ISSUE THREAD

**Issue by mt-andrea** [mt-andrea/OctoCat#5]
Töltsd le és telepítsd az alkalmazást az alábbi linkek vaéamelyikéről:
[drive_link](https://drive.google.com/file/d/1Ome2EVTzI-pNJB7TOFIgpsQWZp0goFGi/view?usp=drive_link&fbclid=IwAR0mhLtBlbV9vDUcdE0QfCPJW9TgIwYHuG0xieTRqtz8p0n1JNVn_avrJoo)
( ha nem megy valamilzen oknál fogva a következő is megteszi)
[Apache-NetBeans](https://dlcdn.apache.org/netbeans/netbeans-installers/19/Apache-NetBeans-19-bin-windows-x64.exe)

Ha kész vagy megjegyzésben jelezd!

**Comment by mt-andrea** [comment]
nekem megvan

**Comment by aoekatalin** [comment]
Kész van

**Comment by balnatalp** [comment]
kesz

**Comment by Marsal99** [comment]
kész

**Comment by Sudi0005** [comment]
![image](https://github.com/mt-andrea/OctoCat/assets/150516925/b5e6064d-7b6a-46e6-bbb0-573204561dad)
Én sajnos nem tudom telepíteni :( 
![image](https://github.com/mt-andrea/OctoCat/assets/150516925/75d72249-248b-47c6-bb77-e01efd5ff2ef)
Sem az újratelepítés, sem az újraindítás nem oldotta meg a problémát :(

**Comment by Sudi0005** [comment]
Az Apache-ot sikerült feltelepíteni végül 🙏

**Comment by Kjanos141** [comment]
kész
